package com.ankit.java.record_concept_jdk_17;

// A BankAccount record that holds account number, holder name, and balance.
public record BankAccount(String accountNumber, String accountHolderName, double balance) {

    // The constructor, getters, equals, hashCode, and toString are
    // automatically generated by the compiler!

    // --- Optional: You can add custom behavior ---

    // 1. Compact Constructor (for validation)
    // This runs AFTER the fields have been assigned but allows you to validate.
    public BankAccount {
        if (balance < 0) {
            throw new IllegalArgumentException("Balance cannot be negative");
        }
    }

    // 2. Custom Method
    public String getFormattedBalance() {
        return String.format("$%.2f", balance);
    }

    // 3. You can also override the auto-generated methods if needed.
    @Override
    public String toString() {
        // You can create a custom toString, or just use the default by not overriding.
        return "Account: " + accountNumber + " | Holder: " + accountHolderName;
    }
}
